<?php
/**
 * @category    RoyalCyberMarketplace
 * @copyright   Copyright (c) 2022 RoyalCyberMarketplace (https://royalcyber.com/)
 *
 * @var $block \RoyalCyberMarketplace\ProductQuestions\Block\Product\Question
 */
// @codingStandardsIgnoreFile
?>

<div id="product-question-container" data-role="product-question"></div>
<?= /* @noEscape */ $block->getChildHtml(); ?>

<script type="text/x-magento-init">
    {
        "*": {
            "RoyalCyberMarketplace_ProductQuestions/js/process-questions": {
                "productQuestionUrl": "<?= /* @noEscape */ $block->getProductQuestionUrl();?>"
            }
        },
        "#product-question-container": {
            "RoyalCyberMarketplace_ProductQuestions/js/process-like-dislike": {
                "likeDislikeUrl": "<?= /* @noEscape */ $block->getLikeDislikeUrl();?>",
                "loadingNumberImage": "<?= /* @noEscape */ $block->getViewFileUrl('RoyalCyberMarketplace_ProductQuestions::images/loading-number.gif'); //phpcs:ignore?>" 
            }
        }
    }
</script>
