<?php
/**
 * @category    RoyalCyberMarketplace
 * @copyright   Copyright (c) 2022 RoyalCyberMarketplace (https://royalcyber.com/)
 *

/** @var \RoyalCyberMarketplace\ProductQuestions\Block\Customer\ListCustomer $block */
// @codingStandardsIgnoreFile
?>
<?php if ($block->getQuestions() && count($block->getQuestions())): ?>
    <div class="table-wrapper questions">
        <table class="data table table-questions" id="my-questions-table">
            <thead>
                <tr>
                    <th scope="col" class="col date"><?= /* @noEscape */ __('Created') ?></th>
                    <th scope="col" class="col item"><?= /* @noEscape */ __('Product Name') ?></th>
                    <th scope="col" class="col description"><?= /* @noEscape */ __('Question') ?></th>
                    <th scope="col" class="col actions"><?= /* @noEscape */ __('Status') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getQuestions() as $question): ?>
                <tr>
                    <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Created')) ?>" class="col date"><?= /* @noEscape */ $block->dateFormat($question->getQuestionCreatedAt()); ?></td>
                    <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Product Name')) ?>" class="col item">
                        <strong class="product-name">
                            <a href="<?= /* @noEscape */ $block->getProductUrl($question->getProductId()); ?>"><?= /* @noEscape */ $block->escapeHtml($question->getProductName()); ?></a>
                        </strong>
                    </td>
                    <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Question')) ?>" class="col description question-list">
                        <?= /* @noEscape */ $block->escapeHtml(nl2br($question->getQuestionDetail())); ?>
                        <h4><?= /* @noEscape */ __('Answers'); ?>: </h4>
                        <?php if (!empty($answers = $block->getAnswerList($question->getQuestionId()))): ?>
                            <ul class="parent">
                            <?php foreach ($answers as $answer): ?>
                                <?php $like = ($answer['likes'] > 0) ? $answer['likes'] : ''; ?>
                                <?php $dislike = ($answer['dislikes'] > 0) ? $answer['dislikes'] : ''; ?>
                                <li>
                                    <p class="table">
                                        <span class="first-character"><?= /* @noEscape */ $answer['first_character'];?></span>
                                        <span class="author-name">
                                            <strong><?= /* @noEscape */ $answer['author_name'];?></strong>
                                            <small class="time"><?= /* @noEscape */ __('Answered by'); ?> <?= /* @noEscape */ $answer['answered_by'];?> <?= /* @noEscape */ __('on'); ?> <?= /* @noEscape */ $answer['created_at'];?></small>
                                        </span>
                                    </p>
                                    <p><?= /* @noEscape */ strip_tags($answer['content'], '<br/><br /><br>');?></p>
                                    <ul class="reply" comment-id="<?= /* @noEscape */ $answer['id']; ?>">
                                        <li title="<?= /* @noEscape */ __('Like'); ?>" like-on="answer" class="like" clicked="false" is="like">
                                            <span>
                                                <span class="number">
                                                    <?= /* @noEscape */ $like;?>
                                                </span>
                                                <?= /* @noEscape */ __('Like'); ?>
                                            </span>
                                        </li>
                                        <li title="<?= /* @noEscape */ __('Dislike'); ?>" dislike-on="answer" class="dislike" clicked="false" is="dislike">
                                            <span>
                                                <span class="number">
                                                    <?= /* @noEscape */ $dislike;?>
                                                </span>
                                                <?= /* @noEscape */ __('Dislike'); ?>
                                            </span>
                                        </li>
                                    </ul>
                                </li>
                            <?php endforeach; ?>
                            </ul>
                        <?php else: ?>
                            <ul>
                                <li><?= /* @noEscape */ __('Our administrator will reply your question soon.'); ?></li>
                            </ul>
                        <?php endif; ?>
                    </td>
                    <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Status')) ?>" class="col actions">
                        <?= /* @noEscape */ $this->helper('RoyalCyberMarketplace\ProductQuestions\Helper\Data')->getStatusText($question->getQuestionStatusId()); ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-reviews-toolbar bottom">
            <?= /* @noEscape */ $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
    <div id="likes-dislikes"></div>
    <script type="text/x-magento-init">
        {
            "#likes-dislikes": {
                "RoyalCyberMarketplace_ProductQuestions/js/process-like-dislike": {
                    "likeDislikeUrl": "<?= /* @noEscape */ $block->getLikeDislikeUrl();?>",
                    "loadingNumberImage": "<?= /* @noEscape */ $block->getViewFileUrl('RoyalCyberMarketplace_ProductQuestions::images/loading-number.gif'); ?>"
                }
            }
        }
    </script>
<?php else: ?>
    <div class="message info empty"><span><?= /* @noEscape */ __('You have submitted no questions.') ?></span></div>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= /* @noEscape */ $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?= /* @noEscape */ __('Back') ?></span>
        </a>
    </div>
</div>
