<?php
/**
 * @category    RoyalCyberMarketplace
 * @copyright   Copyright (c) 2022 RoyalCyberMarketplace (https://royalcyber.com/)
 */

/** @var $block \RoyalCyberMarketplace\ProductQuestions\Block\Customer\Recent */
// @codingStandardsIgnoreFile
?>

<?php if ($block->getQuestions() && count($block->getQuestions())): ?>
<div class="block block-questions-dashboard">
    <div class="block-title">
        <strong><?= /* @noEscape */ __('My Recent Questions') ?></strong>
        <a class="action view" href="<?= /* @noEscape */ $block->getAllQuestionsUrl() ?>"><span><?= /* @noEscape */ __('View All') ?></span></a>
    </div>
    <div class="block-content">
        <table>
            <thead>
                <tr>
                    <th><?= /* @noEscape */ __('Created'); ?></th>
                    <th><?= /* @noEscape */ __('Product Name'); ?></th>
                    <th><?= /* @noEscape */ __('Title'); ?></th>
                    <th><?= /* @noEscape */ __('Status'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getQuestions() as $question): ?>
                <tr>
                    <td><?= /* @noEscape */ $block->dateFormat($question->getQuestionCreatedAt()); ?></td>
                    <td><a href="<?= /* @noEscape */ $block->getProductUrl($question->getProductId()); ?>"><?= /* @noEscape */ $block->escapeHtml($question->getProductName()); ?></a></td>
                    <td><?= /* @noEscape */ $block->escapeHtml($block->truncateString($question->getQuestionDetail())); ?></td>
                    <td><?= /* @noEscape */ $this->helper('RoyalCyberMarketplace\ProductQuestions\Helper\Data')->getStatusText($question->getQuestionStatusId()); ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php endif; ?>
