<?php
/**
 * @category    RoyalCyberMarketplace
 * @copyright   Copyright (c) 2022 RoyalCyberMarketplace (https://royalcyber.com/)
 *
 * @var $block \RoyalCyberMarketplace\ProductQuestions\Block\Form
 */
// @codingStandardsIgnoreFile
?>
<style>
    .question_popup_container {
        display: none;
    }
</style>
<?php if (!$block->getAllowToWrite()): ?>
    <style>
        .question-add {
            display: none;
        }
    </style>
<?php endif; ?>
<div class="question-add">
    <div class="block-title"><strong><?= /* @noEscape */ __('Write Your Own Question') ?></strong></div>
    <div class="block-content">
        <form action="<?= /* @noEscape */ $block->getAction(); ?>" class="question-form" method="post" id="question-form" data-role="product-question-form" data-mage-init='{"validation":{}}'>
            <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
            <input type="hidden" name="type" value="1" id="reply-on-type" />
            <input type="hidden" name="question_id" value="" id="commentId"/>
            <input type="hidden" name="author_name" value="" id="author_name"/>
            <input type="hidden" name="author_email" value="" id="author_email"/>
            <textarea name="detail" id="detail" cols="5" rows="6" placeholder="<?= /* @noEscape */ __('Write Your Own Question') ?>" data-validate="{required:true, minlength:20}"></textarea>
            <div class="actions-toolbar question-form-actions">
                <div class="question-policy">
                    <a href="<?= /* @noEscape */ $block->getQuestionRulesUrl(); ?>" target="_blank"><b><?= /* @noEscape */ __('Question Policies'); ?></b></a>
                </div>
                <div class="primary actions-primary">
                    <button type="button" class="action cancel"><span><?= /* @noEscape */ __('Cancel') ?></span></button>
                    <button type="submit" class="action submit primary"><span><?= /* @noEscape */ __('Submit Question') ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
<?php if ($block->getIsGuest() && !$block->getAllowToWrite() && $block->getIsCustomersAllowToWrite()): ?>
<div class="message info notlogged">
    <?= /* @noEscape */ __('Only registered users can write questions. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginUrl(), $block->getRegisterUrl()) ?>
</div>
<?php endif; ?>
<div id="question-popup-content" class="question_popup_container">
    <?= /* @noEscape */ $block->getChildHtml(); ?>
</div>
<script type="text/x-magento-init">
    {
        "#question-popup-content": {
            "RoyalCyberMarketplace_ProductQuestions/js/question-authentication-popup": {
                "popupTitle": "<?= /* @noEscape */ __('Sending Information'); ?>",
                "innerWidth": "400",
                "parentFormId": "#question-form",
                "titleButtonAnswer": "<?= /* @noEscape */ __('Submit Answer'); ?>",
                "titleButtonQuestion": "<?= /* @noEscape */ __('Submit Question'); ?>",
                "typeSubmit": "1",
                "titleAnswering": "<?= /* @noEscape */ __('Write Your Own Answer') ?>",
                "titleAsking": "<?= /* @noEscape */ __('Write Your Own Question') ?>"
            }
        }
    }
</script>
