<?php
/**
 * @category    RoyalCyberMarketplace
 * @copyright   Copyright (c) 2022 RoyalCyberMarketplace (https://royalcyber.com/)
 *
 * $block \RoyalCyberMarketplace\ProductQuestions\Block\Product\View\ListView
 */
// @codingStandardsIgnoreFile
?>
<?php $questions = $block->getQuestionProductList(); ?>
<?php if (!empty($questions['data'])): ?>
    <?php $nextQuestion = 'next-question'; ?>
    <?php if ($questions['current_page'] == '1'): ?>
        <?php $nextQuestion = ''; ?>
    <div class="box-question-list">
        <div class="block-title">
            <strong><?= /* @noEscape */ __('Customer Questions'); ?></strong>
        </div>
    <?php endif; ?>
        <div class="question-list <?= /* @noEscape */ $nextQuestion; ?>" id="customer-questions-<?= /* @noEscape */ $questions['current_page']; ?>">
            <ul class="parent">
            <?php foreach ($questions['data'] as $question): ?>
                <?php $like = ($question['likes'] > 0) ? $question['likes'] : ''; ?>
                <?php $dislike = ($question['dislikes'] > 0) ? $question['dislikes'] : ''; ?>
                <li>
                    <p class="table">
                        <span class="first-character"><?= /* @noEscape */ $question['first_character'];?></span>
                        <span class="author-name">
                            <strong><?= /* @noEscape */ $question['author_name'];?></strong>
                            <small class="time"><?= /* @noEscape */ __('Asked by'); ?> <?= /* @noEscape */ $question['asked_by'];?> <?= /* @noEscape */ __('on'); ?> <?= /* @noEscape */ $question['created_at'];?></small>
                        </span>
                    </p>
                    <p><?= /* @noEscape */ $question['title'];?></p>
                    <ul class="reply question-parent" comment-id="<?= /* @noEscape */ $question['id']; ?>">
                        <?php if ($questions['allow_to_reply']): ?>
                            <li title="<?= /* @noEscape */ __('Reply'); ?>" reply-on="question" class="reply-on-question reply-on">
                                <span><?= /* @noEscape */ __('Reply'); ?></span>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <ul class="answers">
                        <?php if (empty($question['answers'])): ?>
                            <li class="last-child"><?= /* @noEscape */ __('Our administrator will reply %1\'s question soon.', ucwords($question['author_name'])); ?></li>
                        <?php endif; ?>
                        <?php foreach ($question['answers'] as $answer): ?>
                            <?php $like = ($answer['likes'] > 0) ? $answer['likes'] : ''; ?>
                            <?php $dislike = ($answer['dislikes'] > 0) ? $answer['dislikes'] : ''; ?>
                            <li>
                                <p class="table">
                                    <span class="first-character"><?= /* @noEscape */ $answer['first_character'];?></span>
                                    <span class="author-name">
                                        <strong><?= /* @noEscape */ $answer['author_name'];?></strong>
                                        <small class="time"><?= /* @noEscape */ __('Answered by'); ?> <?= /* @noEscape */ $answer['answered_by'];?> <?= /* @noEscape */ __('on'); ?> <?= /* @noEscape */ $answer['created_at'];?></small>
                                    </span>
                                </p>
                                <p><?= /* @noEscape */ $answer['content'];?></p>
                                <ul class="reply" comment-id="<?= /* @noEscape */ $answer['id']; ?>">
                                    <?php if ($questions['allow_to_reply']): ?>
                                        <li title="<?= /* @noEscape */ __('Reply'); ?>" reply-on="answer" class="reply-on-answer reply-on">
                                            <span><?= /* @noEscape */ __('Reply'); ?></span>
                                        </li>
                                    <?php endif; ?>
                                    <li title="<?= /* @noEscape */ __('Like'); ?>" like-on="answer" class="like" clicked="false" is="like">
                                        <span>
                                            <span class="number">
                                                <?= /* @noEscape */ $like;?>
                                            </span>
                                            <?= /* @noEscape */ __('Like'); ?>
                                        </span>
                                    </li>
                                    <li title="<?= /* @noEscape */ __('Dislike'); ?>" dislike-on="answer" class="dislike" clicked="false" is="dislike">
                                        <span>
                                            <span class="number">
                                                <?= /* @noEscape */ $dislike;?>
                                            </span>
                                            <?= /* @noEscape */ __('Dislike'); ?>
                                        </span>
                                    </li>
                                </ul>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
        <?php if ($questions['current_page'] < $questions['total_page']): ?>
            <div class="question-load-more">
                <a href="<?= /* @noEscape */ $questions['next_url']; ?>" id="question-load-more" previous-page="customer-questions-<?= /* @noEscape */ $questions['current_page']; ?>">
                    <span><?= /* @noEscape */ __('Load more'); ?></span>
                </a>
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('RoyalCyberMarketplace_ProductQuestions::images/question-load-more.gif'); ?>" class="img-loading"/>
            </div>
        <?php endif; ?>
        <?php if ($questions['current_page'] == '1'): ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
